services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: debugphp-server
    hostname: debugphp-server
    user: root
    expose:
      - '8787'
    environment:
      CADDY_HTTP_PORT: '8787'
    volumes:
      - data:/var/www/html/data
    restart: unless-stopped


volumes:
  data:
