services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: debugphp-server
    hostname: debugphp-server
    user: root
    expose:
      - '80'
    environment:
      - CADDY_HTTP_PORT=80
      - SERVICE_FQDN_APP_80
      - STORAGE_PATH=/var/www/html/data
      - SESSION_LIFETIME_HOURS=24
      - SESSION_ID=
    volumes:
      - data:/var/www/html/data
    restart: unless-stopped

volumes:
  data:
