<?php

/**
 * This file is part of the DebugPHP Server.
 *
 * (c) Leon Schmidt <kontakt@callmeleon.de>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * @see https://github.com/CallMeLeon167/debugphp-server
 */

declare(strict_types=1);

namespace DebugPHP\Server\Database;

use PDO;

/**
 * Database access for toolbar metrics.
 *
 * Metrics are key-value pairs sent by the host application via Debug::metric()
 * and displayed live in the dashboard toolbar. Duplicate keys are overwritten
 * via UPSERT logic.
 *
 * Each metric carries a request_id generated once per PHP request in Debug::init().
 * When a metric is sent with a new request_id, all metrics for that session that
 * still carry an older request_id are soft-deleted. The SSE stream picks up those
 * soft-deleted rows, pushes a metric:remove event to the dashboard, and then
 * hard-deletes them.
 *
 * This ensures that metric keys removed from the application code automatically
 * disappear from the dashboard on the next request.
 */
final class MetricRepository
{
    /**
     * The PDO connection for database queries.
     */
    private PDO $pdo;

    /**
     * Creates a new repository with the given connection.
     *
     * @param Connection $connection The database connection.
     */
    public function __construct(Connection $connection)
    {
        $this->pdo = $connection->pdo();
    }

    /**
     * Writes a metric to the database using UPSERT logic.
     *
     * If the key already exists for this session, the value and request_id
     * are updated. Otherwise a new row is inserted.
     *
     * @param string      $sessionId The session this metric belongs to.
     * @param string      $key       The unique metric name.
     * @param string|null $value     The displayed value, or null for label-only display.
     * @param string      $requestId The request lifecycle ID generated by Debug::init().
     *
     * @return void
     */
    public function upsert(string $sessionId, string $key, ?string $value, string $requestId): void
    {
        $stmt = $this->pdo->prepare('
            INSERT INTO metrics (session_id, `key`, value, request_id, updated_at)
            VALUES (:session_id, :key, :value, :request_id, NOW())
            ON DUPLICATE KEY UPDATE
                value      = VALUES(value),
                request_id = VALUES(request_id),
                updated_at = NOW(),
                removed_at = NULL
        ');

        $stmt->execute([
            'session_id' => $sessionId,
            'key'        => $key,
            'value'      => $value,
            'request_id' => $requestId,
        ]);
    }

    /**
     * Soft-deletes all metrics for a session that belong to a different request.
     *
     * Called after each upsert. Any metric that was not sent during the current
     * request (i.e. its request_id differs) is marked as removed. The SSE stream
     * will pick these up and push metric:remove events to the dashboard.
     *
     * @param string $sessionId        The session ID.
     * @param string $currentRequestId The request ID of the current request.
     *
     * @return list<string> The keys that were soft-deleted.
     */
    public function softDeleteStale(string $sessionId, string $currentRequestId): array
    {
        // First collect the keys that will be soft-deleted
        $selectStmt = $this->pdo->prepare('
            SELECT `key`
            FROM metrics
            WHERE session_id = :session_id
              AND request_id != :request_id
              AND removed_at IS NULL
        ');

        $selectStmt->execute([
            'session_id' => $sessionId,
            'request_id' => $currentRequestId,
        ]);

        /** @var list<string> */
        $keys = $selectStmt->fetchAll(PDO::FETCH_COLUMN);

        if ($keys === []) {
            return [];
        }

        // Soft-delete them
        $stmt = $this->pdo->prepare('
            UPDATE metrics
            SET removed_at = NOW()
            WHERE session_id = :session_id
              AND request_id != :request_id
              AND removed_at IS NULL
        ');

        $stmt->execute([
            'session_id' => $sessionId,
            'request_id' => $currentRequestId,
        ]);

        return $keys;
    }

    /**
     * Returns all active (non-removed) metrics for a session.
     *
     * Used by the SSE stream on initial connect to push all current metrics.
     *
     * @param string $sessionId The session ID.
     *
     * @return list<array{key: string, value: string|null, updated_at: string}>
     */
    public function findBySession(string $sessionId): array
    {
        $stmt = $this->pdo->prepare('
            SELECT `key`, value, updated_at
            FROM metrics
            WHERE session_id = :session_id
              AND removed_at IS NULL
            ORDER BY updated_at ASC
        ');

        $stmt->execute(['session_id' => $sessionId]);

        /** @var list<array{key: string, value: string|null, updated_at: string}> */
        return $stmt->fetchAll();
    }

    /**
     * Returns all active metrics updated after the given timestamp.
     *
     * Used by the SSE stream to push only changed metrics each polling cycle.
     *
     * @param string $sessionId The session ID.
     * @param string $after     MySQL datetime string (Y-m-d H:i:s) as lower bound.
     *
     * @return list<array{key: string, value: string|null, updated_at: string}>
     */
    public function findUpdatedAfter(string $sessionId, string $after): array
    {
        $stmt = $this->pdo->prepare('
            SELECT `key`, value, updated_at
            FROM metrics
            WHERE session_id = :session_id
              AND updated_at > :after
              AND removed_at IS NULL
            ORDER BY updated_at ASC
        ');

        $stmt->execute([
            'session_id' => $sessionId,
            'after'      => $after,
        ]);

        /** @var list<array{key: string, value: string|null, updated_at: string}> */
        return $stmt->fetchAll();
    }

    /**
     * Returns all soft-deleted metrics for a session that were removed after the given timestamp.
     *
     * Used by the SSE stream to detect removed metrics and push metric:remove events.
     *
     * @param string $sessionId The session ID.
     * @param string $after     MySQL datetime string (Y-m-d H:i:s) as lower bound.
     *
     * @return list<array{key: string, removed_at: string}>
     */
    public function findRemoved(string $sessionId, string $after): array
    {
        $stmt = $this->pdo->prepare('
            SELECT `key`, removed_at
            FROM metrics
            WHERE session_id = :session_id
              AND removed_at IS NOT NULL
              AND removed_at >= :after
            ORDER BY removed_at ASC
        ');

        $stmt->execute([
            'session_id' => $sessionId,
            'after'      => $after,
        ]);

        /** @var list<array{key: string, removed_at: string}> */
        return $stmt->fetchAll();
    }

    /**
     * Permanently deletes all soft-deleted metrics for a session.
     *
     * Called by the SSE stream after it has pushed metric:remove events for
     * all soft-deleted rows. This keeps the metrics table clean.
     *
     * @param string $sessionId The session ID.
     *
     * @return void
     */
    public function hardDeleteRemoved(string $sessionId): void
    {
        $stmt = $this->pdo->prepare('
            DELETE FROM metrics
            WHERE session_id = :session_id
              AND removed_at IS NOT NULL
        ');

        $stmt->execute(['session_id' => $sessionId]);
    }

    /**
     * Deletes all metrics for a session (active and soft-deleted).
     *
     * This is handled automatically via ON DELETE CASCADE when the session is
     * deleted, but can also be called manually to clear the toolbar.
     *
     * @param string $sessionId The session ID.
     *
     * @return void
     */
    public function deleteBySession(string $sessionId): void
    {
        $stmt = $this->pdo->prepare('DELETE FROM metrics WHERE session_id = :session_id');
        $stmt->execute(['session_id' => $sessionId]);
    }
}
