<?php

/**
 * This file is part of the DebugPHP Server.
 *
 * (c) Leon Schmidt <kontakt@callmeleon.de>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * @see https://github.com/CallMeLeon167/debugphp-server
 */

declare(strict_types=1);

namespace DebugPHP\Server\Storage;

/**
 * File-based storage for toolbar metrics.
 *
 * All metrics for a session are stored in a single JSON file as a keyed array.
 * Each metric entry contains: key, value, request_id, updated_at, removed_at.
 *
 * File locking (flock) is used for all write operations to prevent race conditions
 * when multiple requests update metrics for the same session concurrently.
 *
 * The soft-delete lifecycle works identically to the database version:
 *   1. upsert()            — writes or updates a metric
 *   2. softDeleteStale()   — marks metrics from older requests as removed
 *   3. findRemoved()       — SSE stream reads removed metrics
 *   4. hardDeleteRemoved() — SSE stream permanently removes them
 */
final class MetricRepository
{
    /**
     * The storage path manager.
     *
     * @var StoragePath
     */
    private StoragePath $storage;

    /**
     * Creates a new repository with the given storage path.
     *
     * @param StoragePath $storage The storage path manager.
     */
    public function __construct(StoragePath $storage)
    {
        $this->storage = $storage;
    }

    /**
     * Writes a metric using UPSERT logic.
     *
     * If the key already exists for this session, the value and request_id
     * are updated. Otherwise a new metric is inserted.
     * Any previously soft-deleted state is cleared on upsert.
     *
     * @param string      $sessionId The session this metric belongs to.
     * @param string      $key       The unique metric name.
     * @param string|null $value     The displayed value, or null for label-only display.
     * @param string      $requestId The request lifecycle ID generated by Debug::init().
     *
     * @return void
     */
    public function upsert(string $sessionId, string $key, ?string $value, string $requestId): void
    {
        $this->withLockedMetrics($sessionId, function (array &$metrics) use ($key, $value, $requestId): void {
            $metrics[$key] = [
                'key'        => $key,
                'value'      => $value,
                'request_id' => $requestId,
                'updated_at' => date('Y-m-d H:i:s'),
                'removed_at' => null,
            ];
        });
    }

    /**
     * Soft-deletes all metrics for a session that belong to a different request.
     *
     * Called after each upsert. Any metric that was not sent during the current
     * request (i.e. its request_id differs) is marked as removed. The SSE stream
     * will pick these up and push metric:remove events to the dashboard.
     *
     * @param string $sessionId        The session ID.
     * @param string $currentRequestId The request ID of the current request.
     *
     * @return list<string> The keys that were soft-deleted.
     */
    public function softDeleteStale(string $sessionId, string $currentRequestId): array
    {
        /** @var list<string> $deletedKeys */
        $deletedKeys = [];

        $this->withLockedMetrics($sessionId, function (array &$metrics) use ($currentRequestId, &$deletedKeys): void {
            $now = date('Y-m-d H:i:s');

            foreach ($metrics as $key => &$metric) {
                if ($metric['request_id'] !== $currentRequestId && $metric['removed_at'] === null) {
                    $metric['removed_at'] = $now;
                    $deletedKeys[]        = (string) $key;
                }
            }
            unset($metric);
        });

        return $deletedKeys;
    }

    /**
     * Returns all active (non-removed) metrics for a session.
     *
     * Used by the SSE stream on initial connect to push all current metrics.
     *
     * @param string $sessionId The session ID.
     *
     * @return list<array{key: string, value: string|null, updated_at: string}>
     */
    public function findBySession(string $sessionId): array
    {
        $metrics = $this->readMetrics($sessionId);

        /** @var list<array{key: string, value: string|null, updated_at: string}> $result */
        $result = [];

        foreach ($metrics as $metric) {
            if ($metric['removed_at'] !== null) {
                continue;
            }

            $result[] = [
                'key'        => $metric['key'],
                'value'      => $metric['value'],
                'updated_at' => $metric['updated_at'],
            ];
        }

        // Sort by updated_at ascending
        usort($result, static function (array $a, array $b): int {
            return strcmp($a['updated_at'], $b['updated_at']);
        });

        return $result;
    }

    /**
     * Returns all active metrics updated after the given timestamp.
     *
     * Used by the SSE stream to push only changed metrics each polling cycle.
     *
     * @param string $sessionId The session ID.
     * @param string $after     Datetime string (Y-m-d H:i:s) as lower bound.
     *
     * @return list<array{key: string, value: string|null, updated_at: string}>
     */
    public function findUpdatedAfter(string $sessionId, string $after): array
    {
        $metrics = $this->readMetrics($sessionId);

        /** @var list<array{key: string, value: string|null, updated_at: string}> $result */
        $result = [];

        foreach ($metrics as $metric) {
            if ($metric['removed_at'] !== null) {
                continue;
            }

            if (strcmp($metric['updated_at'], $after) <= 0) {
                continue;
            }

            $result[] = [
                'key'        => $metric['key'],
                'value'      => $metric['value'],
                'updated_at' => $metric['updated_at'],
            ];
        }

        usort($result, static function (array $a, array $b): int {
            return strcmp($a['updated_at'], $b['updated_at']);
        });

        return $result;
    }

    /**
     * Returns all soft-deleted metrics for a session that were removed after the given timestamp.
     *
     * Used by the SSE stream to detect removed metrics and push metric:remove events.
     *
     * @param string $sessionId The session ID.
     * @param string $after     Datetime string (Y-m-d H:i:s) as lower bound.
     *
     * @return list<array{key: string, removed_at: string}>
     */
    public function findRemoved(string $sessionId, string $after): array
    {
        $metrics = $this->readMetrics($sessionId);

        /** @var list<array{key: string, removed_at: string}> $result */
        $result = [];

        foreach ($metrics as $metric) {
            if ($metric['removed_at'] === null) {
                continue;
            }

            if (strcmp($metric['removed_at'], $after) < 0) {
                continue;
            }

            $result[] = [
                'key'        => $metric['key'],
                'removed_at' => $metric['removed_at'],
            ];
        }

        usort($result, static function (array $a, array $b): int {
            return strcmp($a['removed_at'], $b['removed_at']);
        });

        return $result;
    }

    /**
     * Permanently deletes all soft-deleted metrics for a session.
     *
     * Called by the SSE stream after it has pushed metric:remove events for
     * all soft-deleted rows. This keeps the metrics file clean.
     *
     * @param string $sessionId The session ID.
     *
     * @return void
     */
    public function hardDeleteRemoved(string $sessionId): void
    {
        $this->withLockedMetrics($sessionId, static function (array &$metrics): void {
            foreach ($metrics as $key => $metric) {
                if ($metric['removed_at'] !== null) {
                    unset($metrics[$key]);
                }
            }
        });
    }

    /**
     * Deletes all metrics for a session (active and soft-deleted).
     *
     * @param string $sessionId The session ID.
     *
     * @return void
     */
    public function deleteBySession(string $sessionId): void
    {
        $file = $this->storage->metricsFile($sessionId);

        if (is_file($file)) {
            unlink($file);
        }
    }

    /**
     * Reads all metrics for a session from disk.
     *
     * Returns an empty array if the file does not exist.
     *
     * @param string $sessionId The session ID.
     *
     * @return array<string, array{key: string, value: string|null, request_id: string, updated_at: string, removed_at: string|null}>
     */
    private function readMetrics(string $sessionId): array
    {
        $file = $this->storage->metricsFile($sessionId);

        if (!is_file($file)) {
            return [];
        }

        $content = file_get_contents($file);

        if ($content === false || $content === '') {
            return [];
        }

        /** @var array<string, array{key: string, value: string|null, request_id: string, updated_at: string, removed_at: string|null}> */
        return json_decode($content, true, 512, JSON_THROW_ON_ERROR);
    }

    /**
     * Executes a callback with exclusive file-lock access to the metrics file.
     *
     * Reads the current metrics, passes them by reference to the callback,
     * then writes the modified data back. Uses flock() to prevent race conditions.
     *
     * @param string                                                                                                                                     $sessionId The session ID.
     * @param \Closure(array<string, array{key: string, value: string|null, request_id: string, updated_at: string, removed_at: string|null}>&): void $callback  The callback that modifies the metrics array.
     *
     * @return void
     */
    private function withLockedMetrics(string $sessionId, \Closure $callback): void
    {
        $file = $this->storage->metricsFile($sessionId);

        $handle = fopen($file, 'c+');

        if ($handle === false) {
            throw new \RuntimeException('Failed to open metrics file: ' . $file);
        }

        flock($handle, LOCK_EX);

        $content = stream_get_contents($handle);

        /** @var array<string, array{key: string, value: string|null, request_id: string, updated_at: string, removed_at: string|null}> $metrics */
        $metrics = $content !== false && $content !== '' ? json_decode($content, true, 512, JSON_THROW_ON_ERROR) : [];

        $callback($metrics);

        fseek($handle, 0);
        ftruncate($handle, 0);
        fwrite($handle, json_encode($metrics, JSON_THROW_ON_ERROR | JSON_UNESCAPED_UNICODE));
        fflush($handle);
        flock($handle, LOCK_UN);
        fclose($handle);
    }
}
