<?php

/**
 * This file is part of the DebugPHP Server.
 *
 * (c) Leon Schmidt <kontakt@callmeleon.de>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * @see https://github.com/CallMeLeon167/debugphp-server
 *
 * ─────────────────────────────────────────────────────────
 * SETUP WIZARD
 *
 * Interactive setup for the DebugPHP server.
 * Handles .env creation, connection testing, and table setup.
 *
 * To re-run the setup wizard after initial configuration,
 * change the flag below to true.
 * ─────────────────────────────────────────────────────────
 */

declare(strict_types=1);

/**
 * Set this to true to allow re-running the setup wizard
 * after the server has already been configured.
 */
const ALLOW_SETUP = false;

// ─── Autoloader ──────────────────────────────────────────
$autloader = __DIR__ . '/../vendor/autoload.php';
if (file_exists($autloader)) {
    require_once $autloader;
} else {
    showRunComposerInstall();
    exit;
}

// ─── Check if Already Configured ─────────────────────────
$rootDir = dirname(__DIR__);
$envPath = $rootDir . '/.env';
$envExists = file_exists($envPath);
$isConfigured = false;

if ($envExists) {
    $dotenv = Dotenv\Dotenv::createImmutable($rootDir);
    $loadedEnv = $dotenv->load();

    try {
        $dsn = sprintf(
            'mysql:host=%s;port=%s;dbname=%s;charset=utf8mb4',
            $loadedEnv['DB_HOST'] ?? 'localhost',
            $loadedEnv['DB_PORT'] ?? '3306',
            $loadedEnv['DB_DATABASE'] ?? 'debugphp'
        );

        $pdo = new PDO($dsn, $loadedEnv['DB_USERNAME'] ?? 'root', $loadedEnv['DB_PASSWORD'] ?? '', [
            PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
            PDO::ATTR_TIMEOUT => 3,
        ]);

        /** @var list<string> */
        $tables = $pdo->query('SHOW TABLES')->fetchAll(PDO::FETCH_COLUMN);

        if (in_array('sessions', $tables, true) && in_array('entries', $tables, true)) {
            $isConfigured = true;
        }
    } catch (\Throwable $e) {
        // Not configured or connection error — continue to wizard
    }
}

// Block access if already configured and ALLOW_SETUP is false
if ($isConfigured && !ALLOW_SETUP) {
    if ($_SERVER['REQUEST_METHOD'] === 'POST') {
        header('Content-Type: application/json; charset=utf-8');
        echo json_encode(['success' => false, 'message' => 'Setup is locked. Set ALLOW_SETUP to true in setup/index.php to reconfigure.']);
        exit;
    }

    showConfiguredScreen();
    exit;
}

// ─── Handle AJAX Requests ────────────────────────────────
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    header('Content-Type: application/json; charset=utf-8');

    $raw = file_get_contents('php://input');
    $body = $raw !== false ? json_decode($raw, true) : null;

    if (!is_array($body) || !isset($body['action'])) {
        echo json_encode(['success' => false, 'message' => 'Invalid request.']);
        exit;
    }

    $action = $body['action'];

    // ── Test Connection ──────────────────────────────────
    if ($action === 'test') {
        $host = $body['db_host'] ?? 'localhost';
        $port = $body['db_port'] ?? '3306';
        $database = $body['db_database'] ?? '';
        $username = $body['db_username'] ?? 'root';
        $password = $body['db_password'] ?? '';

        try {
            $dsn = "mysql:host={$host};port={$port};dbname={$database};charset=utf8mb4";
            $pdo = new PDO($dsn, $username, $password, [
                PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
                PDO::ATTR_TIMEOUT => 5,
            ]);

            /** @var array{Value: string}|false */
            $version = $pdo->query("SHOW VARIABLES LIKE 'version'")->fetch(PDO::FETCH_ASSOC);
            $versionStr = is_array($version) ? $version['Value'] : 'unknown';

            echo json_encode([
                'success' => true,
                'message' => "Connection successful! Server: MySQL/MariaDB {$versionStr}",
            ]);
        } catch (\Throwable $e) {
            echo json_encode([
                'success' => false,
                'message' => 'Connection failed: ' . $e->getMessage(),
            ]);
        }

        exit;
    }

    // ── Save .env ────────────────────────────────────────
    if ($action === 'save_env') {
        $envContent = "# DebugPHP Server Configuration\n";
        $envContent .= "# Generated by setup wizard on " . date('Y-m-d H:i:s') . "\n\n";
        $envContent .= "# Database Connection\n";
        $envContent .= "DB_HOST=" . ($body['db_host'] ?? 'localhost') . "\n";
        $envContent .= "DB_PORT=" . ($body['db_port'] ?? '3306') . "\n";
        $envContent .= "DB_DATABASE=" . ($body['db_database'] ?? 'debugphp') . "\n";
        $envContent .= "DB_USERNAME=" . ($body['db_username'] ?? 'root') . "\n";
        $envContent .= "DB_PASSWORD=" . ($body['db_password'] ?? '') . "\n\n";
        $envContent .= "# Session Settings\n";
        $envContent .= "SESSION_LIFETIME_HOURS=" . ($body['session_lifetime'] ?? '24') . "\n";

        if (file_put_contents(dirname(__DIR__) . '/.env', $envContent) === false) {
            echo json_encode([
                'success' => false,
                'message' => 'Failed to write .env file. Check file permissions for: ' . dirname(__DIR__),
            ]);
            exit;
        }

        echo json_encode([
            'success' => true,
            'message' => '.env file saved successfully.',
        ]);

        exit;
    }

    // ── Create Tables ────────────────────────────────────
    if ($action === 'setup') {
        $host = $body['db_host'] ?? 'localhost';
        $port = $body['db_port'] ?? '3306';
        $database = $body['db_database'] ?? '';
        $username = $body['db_username'] ?? 'root';
        $password = $body['db_password'] ?? '';

        try {
            $dsn = "mysql:host={$host};port={$port};dbname={$database};charset=utf8mb4";
            $pdo = new PDO($dsn, $username, $password, [
                PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
            ]);

            $pdo->exec('
                CREATE TABLE IF NOT EXISTS sessions (
                    id VARCHAR(32) NOT NULL PRIMARY KEY,
                    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    expires_at DATETIME NOT NULL,
                    INDEX idx_expires (expires_at)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            ');

            $pdo->exec('
                CREATE TABLE IF NOT EXISTS entries (
                    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
                    session_id VARCHAR(32) NOT NULL,
                    data JSON NOT NULL,
                    label VARCHAR(255) NOT NULL DEFAULT \'\',
                    color VARCHAR(20) NOT NULL DEFAULT \'gray\',
                    type VARCHAR(50) NOT NULL DEFAULT \'info\',
                    origin_file VARCHAR(255) NOT NULL DEFAULT \'\',
                    origin_line INT UNSIGNED NOT NULL DEFAULT 0,
                    timestamp DOUBLE NOT NULL,
                    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    INDEX idx_session_id (session_id),
                    INDEX idx_session_created (session_id, id),
                    FOREIGN KEY (session_id) REFERENCES sessions(id) ON DELETE CASCADE
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            ');

            echo json_encode([
                'success' => true,
                'message' => 'Tables created successfully! Your DebugPHP server is ready.',
            ]);
        } catch (\Throwable $e) {
            echo json_encode([
                'success' => false,
                'message' => 'Setup failed: ' . $e->getMessage(),
            ]);
        }

        exit;
    }

    echo json_encode(['success' => false, 'message' => 'Unknown action.']);
    exit;
}

// ─── Load Existing .env Values ───────────────────────────
$envValues = [
    'db_host' => 'localhost',
    'db_port' => '3306',
    'db_database' => 'debugphp',
    'db_username' => 'root',
    'db_password' => '',
    'session_lifetime' => '24',
];

if ($envExists) {
    foreach ($loadedEnv as $key => $value) {
        match ($key) {
            'DB_HOST' => $envValues['db_host'] = $value,
            'DB_PORT' => $envValues['db_port'] = $value,
            'DB_DATABASE' => $envValues['db_database'] = $value,
            'DB_USERNAME' => $envValues['db_username'] = $value,
            'DB_PASSWORD' => $envValues['db_password'] = $value,
            'SESSION_LIFETIME_HOURS' => $envValues['session_lifetime'] = $value,
            default => null,
        };
    }
}

/**
 * Helper to safely output a value in an HTML attribute.
 */
function e(string $value): string
{
    return htmlspecialchars($value, ENT_QUOTES | ENT_HTML5, 'UTF-8');
}

/**
 * Renders a standalone page indicating the server is already configured.
 */
function showConfiguredScreen(): void
{
?>
    <!DOCTYPE html>
    <html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>DebugPHP — Setup</title>
        <link href="/assets/fonts/fonts.css" rel="stylesheet">
        <link rel="stylesheet" href="/setup/styles.css">
    </head>

    <body>
        <div class="card configured-card">
            <div class="icon">&#10003;</div>
            <h2>DebugPHP is configured and ready!</h2>
            <p>Your server is set up and the database tables exist.</p>
            <p>Everything is working — you can start debugging.</p>
            <div class="hint">
                Need to reconfigure? Set
                <br>
                <code>ALLOW_SETUP</code> to <code>true</code> in <code>setup/index.php</code>
            </div>
            <a href="/" class="btn-open-dashboard">Open Dashboard &rarr;</a>
        </div>
    </body>

    </html>
<?php
}

function showRunComposerInstall(): void
{
?>
    <!DOCTYPE html>
    <html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>DebugPHP — Setup</title>
        <link href="/assets/fonts/fonts.css" rel="stylesheet">
        <link rel="stylesheet" href="/setup/styles.css">
    </head>

    <body>
        <div class="card configured-card">
            <div class="icon">&#9888;</div>
            <h2>DebugPHP not ready yet</h2>
            <p>To setup DebugPHP, please run</p>
            <div class="hint space-m">
                <code>composer install</code>
            </div>
            <p>in the project root. This will install all necessary dependencies.</p><br>
            <a href="/setup/" class="btn btn-primary">Refresh Page</a>
        </div>
    </body>

    </html>
<?php
}

?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DebugPHP — Setup Wizard</title>
    <link href="/assets/fonts/fonts.css" rel="stylesheet">
    <link rel="stylesheet" href="/setup/styles.css">
</head>

<body>

    <div class="wizard">
        <div class="wizard-header">
            <div class="wizard-logo"> DebugPHP</div>
            <div class="wizard-subtitle">Setup Wizard</div>
        </div>

        <?php // If we reach this point, either !isConfigured or ALLOW_SETUP is true 
        ?>

        <!-- Steps -->
        <div class="steps-indicator">
            <div class="step-dot active" id="stepDot1">1</div>
            <div class="step-line" id="stepLine1"></div>
            <div class="step-dot" id="stepDot2">2</div>
            <div class="step-line" id="stepLine2"></div>
            <div class="step-dot" id="stepDot3">&#10003;</div>
        </div>

        <!-- Step 1: Configuration -->
        <div id="step1" class="card">
            <div class="card-title">Database Configuration</div>
            <div class="card-desc">
                <p>Enter your MySQL/MariaDB credentials below.</p>
                <?php if ($envExists): ?>
                    <span class="env-badge exists">&#10003; .env file found — values loaded</span>
                <?php else: ?>
                    <span class="env-badge missing">&#9888; No .env file — please fill in your credentials</span>
                <?php endif; ?>
            </div>

            <div class="form-row">
                <div class="form-group">
                    <label class="form-label">Host</label>
                    <input class="form-input" id="dbHost" type="text" value="<?= e($envValues['db_host']) ?>" placeholder="localhost">
                </div>
                <div class="form-group">
                    <label class="form-label">Port</label>
                    <input class="form-input" id="dbPort" type="text" value="<?= e($envValues['db_port']) ?>" placeholder="3306">
                </div>
            </div>

            <div class="form-row full">
                <div class="form-group">
                    <label class="form-label">Database Name</label>
                    <input class="form-input" id="dbDatabase" type="text" value="<?= e($envValues['db_database']) ?>" placeholder="debugphp">
                </div>
            </div>

            <div class="form-row">
                <div class="form-group">
                    <label class="form-label">Username</label>
                    <input class="form-input" id="dbUsername" type="text" value="<?= e($envValues['db_username']) ?>" placeholder="root">
                </div>
                <div class="form-group">
                    <label class="form-label">Password</label>
                    <input class="form-input" id="dbPassword" type="password" value="<?= e($envValues['db_password']) ?>" placeholder="••••••••">
                </div>
            </div>

            <div class="form-divider"></div>

            <div class="form-row full">
                <div class="form-group">
                    <label class="form-label">Session Lifetime (hours)</label>
                    <input class="form-input" id="sessionLifetime" type="number" value="<?= e($envValues['session_lifetime']) ?>" placeholder="24" min="1" style="max-width:200px;">
                </div>
            </div>

            <div id="alertTest" class="alert"></div>

            <div class="btn-row">
                <button class="btn btn-secondary" id="btnTest" onclick="testConnection()">
                    <span class="btn-text">&#128268; Test Connection</span>
                    <span class="spinner"></span>
                </button>
                <button class="btn btn-primary" id="btnNext" onclick="saveEnvAndNext()" disabled>
                    <span class="btn-text">Save &amp; Continue &rarr;</span>
                    <span class="spinner"></span>
                </button>
            </div>
        </div>

        <!-- Step 2: Create Tables -->
        <div id="step2" class="card" style="display:none;">
            <div class="card-title">Create Database Tables</div>
            <div class="card-desc">
                Your .env file has been saved. Click the button below to create the required database tables.
            </div>

            <div class="code-box">
                <span class="kw">CREATE TABLE</span> <span class="val">sessions</span> (...)<br>
                <span class="kw">CREATE TABLE</span> <span class="val">entries</span> (...)
            </div>

            <div id="alertSetup" class="alert"></div>

            <div class="btn-row">
                <button class="btn btn-secondary" onclick="goBack()">
                    &larr; Back
                </button>
                <button class="btn btn-primary" id="btnSetup" onclick="runSetup()">
                    <span class="btn-text">Run Setup</span>
                    <span class="spinner"></span>
                </button>
            </div>
        </div>

        <!-- Step 3: Done -->
        <div id="step3" class="card" style="display:none;">
            <div class="success-screen">
                <div class="success-icon">&#9889;</div>
                <h2>You're all set!</h2>
                <p>Your DebugPHP server is configured and ready to go.</p>
                <p>Open the dashboard and create your first debug session.</p>
                <a href="/" class="btn-open-dashboard">Open Dashboard &rarr;</a>
            </div>
        </div>

    </div>

    <script src="/setup/script.js"></script>
</body>

</html>