<?php

/**
 * This file is part of the DebugPHP Server.
 *
 * (c) Leon Schmidt <kontakt@callmeleon.de>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * @see https://github.com/CallMeLeon167/debugphp-server
 */

declare(strict_types=1);

/**
 * Handles all setup logic for the DebugPHP server.
 *
 * Responsible for:
 * - Checking whether the server is already configured
 * - Testing the storage directory permissions
 * - Writing the .env file
 * - Creating the storage directories
 * - Loading existing .env values for pre-filling the form
 */
final class SetupManager
{
    /**
     * Absolute path to the project root directory.
     *
     * @var string
     */
    private string $rootDir;

    /**
     * Absolute path to the .env file.
     *
     * @var string
     */
    private string $envPath;

    public function __construct()
    {
        $this->rootDir = dirname(__DIR__);
        $this->envPath = $this->rootDir . '/.env';
    }

    /**
     * Returns true if the .env file exists.
     *
     * @return bool
     */
    public function envExists(): bool
    {
        return file_exists($this->envPath);
    }

    /**
     * Checks whether the server is fully configured.
     *
     * Considers the server configured when the .env file exists
     * and the storage directory is writable with the correct structure.
     *
     * @param array<string, string> $env The loaded environment variables.
     *
     * @return bool
     */
    public function isConfigured(array $env): bool
    {
        if (!$this->envExists()) {
            return false;
        }

        $storagePath = $env['STORAGE_PATH'] ?? 'data';

        if (!str_starts_with($storagePath, '/')) {
            $storagePath = $this->rootDir . '/' . $storagePath;
        }

        return is_dir($storagePath . '/sessions')
            && is_dir($storagePath . '/entries')
            && is_dir($storagePath . '/metrics')
            && is_dir($storagePath . '/environments');
    }

    /**
     * Loads existing .env values for pre-filling the setup form.
     *
     * Returns defaults for any missing key.
     *
     * @param array<string, string> $env The loaded environment variables.
     *
     * @return array<string, string>
     */
    public function loadFormValues(array $env): array
    {
        return [
            'storage_path'     => $env['STORAGE_PATH']           ?? 'data',
            'session_lifetime' => $env['SESSION_LIFETIME_HOURS'] ?? '24',
            'session_mode'     => ($env['SESSION_ID'] ?? '') !== '' ? 'static' : 'random',
            'session_id'       => $env['SESSION_ID']             ?? '',
        ];
    }

    /**
     * Tests whether the storage directory is writable.
     *
     * @param array<string, mixed> $body The decoded request body.
     *
     * @return array{success: bool, message: string}
     */
    public function testStorage(array $body): array
    {
        $storagePath = is_string($body['storage_path'] ?? null) ? $body['storage_path'] : 'data';

        if (!str_starts_with($storagePath, '/')) {
            $storagePath = $this->rootDir . '/' . $storagePath;
        }

        if (!is_dir($storagePath)) {
            $created = @mkdir($storagePath, 0755, true);

            if (!$created) {
                return [
                    'success' => false,
                    'message' => 'Cannot create storage directory: ' . $storagePath,
                ];
            }
        }

        if (!is_writable($storagePath)) {
            return [
                'success' => false,
                'message' => 'Storage directory is not writable: ' . $storagePath,
            ];
        }

        return [
            'success' => true,
            'message' => 'Storage directory is writable and ready.',
        ];
    }

    /**
     * Writes the .env file from the submitted form data.
     *
     * @param array<string, mixed> $body The decoded request body.
     *
     * @return array{success: bool, message: string}
     */
    public function saveEnv(array $body): array
    {
        $content  = "# DebugPHP Server Configuration\n";
        $content .= "# Generated by setup wizard on " . date('Y-m-d H:i:s') . "\n\n";
        $content .= "# Storage\n";
        $content .= 'STORAGE_PATH=' . (is_string($body['storage_path'] ?? null) ? $body['storage_path'] : 'data') . "\n\n";
        $content .= "# Session Settings\n";
        $content .= 'SESSION_LIFETIME_HOURS=' . (is_string($body['session_lifetime'] ?? null) ? $body['session_lifetime'] : '24') . "\n";

        $sessionMode = is_string($body['session_mode'] ?? null) ? $body['session_mode'] : 'random';
        $sessionId = '';

        if ($sessionMode === 'static' && is_string($body['session_id'] ?? null) && $body['session_id'] !== '') {
            $sessionId = $body['session_id'];
        }

        $content .= 'SESSION_ID=' . $sessionId . "\n";

        if (file_put_contents($this->envPath, $content) === false) {
            return [
                'success' => false,
                'message' => 'Failed to write .env file. Check permissions for: ' . $this->rootDir,
            ];
        }

        return ['success' => true, 'message' => '.env file saved successfully.'];
    }

    /**
     * Creates the required storage directories.
     *
     * Safe to call multiple times — only creates directories that don't exist yet.
     *
     * @param array<string, mixed> $body The decoded request body.
     *
     * @return array{success: bool, message: string}
     */
    public function createDirectories(array $body): array
    {
        $storagePath = is_string($body['storage_path'] ?? null) ? $body['storage_path'] : 'data';

        if (!str_starts_with($storagePath, '/')) {
            $storagePath = $this->rootDir . '/' . $storagePath;
        }

        $dirs = [
            $storagePath,
            $storagePath . '/sessions',
            $storagePath . '/entries',
            $storagePath . '/metrics',
            $storagePath . '/environments',
        ];

        try {
            foreach ($dirs as $dir) {
                if (!is_dir($dir)) {
                    mkdir($dir, 0755, true);
                }
            }

            return [
                'success' => true,
                'message' => 'Storage directories created successfully! Your DebugPHP server is ready.',
            ];
        } catch (\Throwable $e) {
            return [
                'success' => false,
                'message' => 'Setup failed: ' . $e->getMessage(),
            ];
        }
    }
}
